export enum ErrorMessage {
    PostWithThisTitleAlreadyExists = "POST_WITH_THIS_TITLE_ALREADY_EXISTS",
    ServerError = "INTERNAL_SERVER_ERROR",
    CategoryAlreadyExists = "CATEGORY_ALREADY_EXISTS",
    CategoryNotFound = "CATEGORY_NOT_FOUND",
    VolumeAlreadyExists = "CATEGORY_ALREADY_EXISTS",
    VolumeNotFound = "CATEGORY_NOT_FOUND",
    ProductAlreadyExists = "PRODUCT_ALREADY_EXISTS",
    ProductNotFound = "PRODUCT_NOT_FOUND",
    ValidationError = "VALIDATION_ERROR",
    EmailAlreadyTaken = "EMAIL_ALREADY_TAKEN",
    Unauthorized = "UNAUTHORIZED",
    UserNotFound = "USER_NOT_FOUND",
    IncorrectPassword = "INCORRECT_PASSWORD",
    CartEmpty = "CART_EMPTY",
    FileRequired = "FILE_REQUIRED",
    ArticleAlreadyExists = "ARTICLE_ALREADY_EXISTS",
    ArticleNotFound = "ARTICLE_NOT_FOUND",
}